name: Build Custom Otel Image

on:
  push:
    branches: [ main ]

jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: OCB Build
        run: chmod +x "${GITHUB_WORKSPACE}/builder.sh && ${GITHUB_WORKSPACE}/builder.sh

    - name: Buildah Build
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: rubenmgx
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Dockerfile

    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/rugomez
        username: ${{ secrets.QUAY_BOT_USER }}
        password: ${{ secrets.QUAY_BOT_PASSWORD }}
